// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/message.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Sorting
type ListingOptions_Order int32

const (
	ListingOptions_ASC  ListingOptions_Order = 0
	ListingOptions_DESC ListingOptions_Order = 1
)

var ListingOptions_Order_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}

var ListingOptions_Order_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x ListingOptions_Order) String() string {
	return proto.EnumName(ListingOptions_Order_name, int32(x))
}

func (ListingOptions_Order) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_14bbce0197584590, []int{0, 0}
}

type ListingOptions struct {
	// Pagination
	Page                 uint32                        `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              uint32                        `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Filters              []*ListingOptions_FilterParam `protobuf:"bytes,10,rep,name=filters,proto3" json:"filters,omitempty"`
	SortField            string                        `protobuf:"bytes,20,opt,name=sort_field,json=sortField,proto3" json:"sort_field,omitempty"`
	SortOrder            ListingOptions_Order          `protobuf:"varint,21,opt,name=sort_order,json=sortOrder,proto3,enum=github.com.timbertomgmbh.listings.ListingOptions_Order" json:"sort_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ListingOptions) Reset()         { *m = ListingOptions{} }
func (m *ListingOptions) String() string { return proto.CompactTextString(m) }
func (*ListingOptions) ProtoMessage()    {}
func (*ListingOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_14bbce0197584590, []int{0}
}

func (m *ListingOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingOptions.Unmarshal(m, b)
}
func (m *ListingOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingOptions.Marshal(b, m, deterministic)
}
func (m *ListingOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingOptions.Merge(m, src)
}
func (m *ListingOptions) XXX_Size() int {
	return xxx_messageInfo_ListingOptions.Size(m)
}
func (m *ListingOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ListingOptions proto.InternalMessageInfo

func (m *ListingOptions) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListingOptions) GetPerPage() uint32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *ListingOptions) GetFilters() []*ListingOptions_FilterParam {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *ListingOptions) GetSortField() string {
	if m != nil {
		return m.SortField
	}
	return ""
}

func (m *ListingOptions) GetSortOrder() ListingOptions_Order {
	if m != nil {
		return m.SortOrder
	}
	return ListingOptions_ASC
}

// Filtering
type ListingOptions_FilterParam struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListingOptions_FilterParam) Reset()         { *m = ListingOptions_FilterParam{} }
func (m *ListingOptions_FilterParam) String() string { return proto.CompactTextString(m) }
func (*ListingOptions_FilterParam) ProtoMessage()    {}
func (*ListingOptions_FilterParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_14bbce0197584590, []int{0, 0}
}

func (m *ListingOptions_FilterParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingOptions_FilterParam.Unmarshal(m, b)
}
func (m *ListingOptions_FilterParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingOptions_FilterParam.Marshal(b, m, deterministic)
}
func (m *ListingOptions_FilterParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingOptions_FilterParam.Merge(m, src)
}
func (m *ListingOptions_FilterParam) XXX_Size() int {
	return xxx_messageInfo_ListingOptions_FilterParam.Size(m)
}
func (m *ListingOptions_FilterParam) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingOptions_FilterParam.DiscardUnknown(m)
}

var xxx_messageInfo_ListingOptions_FilterParam proto.InternalMessageInfo

func (m *ListingOptions_FilterParam) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *ListingOptions_FilterParam) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func init() {
	proto.RegisterEnum("github.com.timbertomgmbh.listings.ListingOptions_Order", ListingOptions_Order_name, ListingOptions_Order_value)
	proto.RegisterType((*ListingOptions)(nil), "github.com.timbertomgmbh.listings.ListingOptions")
	proto.RegisterType((*ListingOptions_FilterParam)(nil), "github.com.timbertomgmbh.listings.ListingOptions.FilterParam")
}

func init() {
	proto.RegisterFile("rpc/message.proto", fileDescriptor_14bbce0197584590)
}

var fileDescriptor_14bbce0197584590 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4d, 0x4b, 0x33, 0x31,
	0x14, 0x85, 0xdf, 0xe9, 0xc7, 0xdb, 0xf6, 0x16, 0x4b, 0x0d, 0x15, 0xc6, 0x82, 0x30, 0x76, 0x35,
	0x22, 0xcd, 0x40, 0x5d, 0x88, 0x0b, 0x17, 0x5a, 0xed, 0x4a, 0x68, 0x99, 0x82, 0x82, 0x9b, 0x32,
	0xd3, 0xa6, 0x69, 0x60, 0xd2, 0xc4, 0x9b, 0x74, 0xe1, 0x1f, 0xf6, 0x77, 0x48, 0x32, 0xd6, 0x8f,
	0x95, 0xb8, 0xbb, 0xe7, 0x5c, 0x72, 0xce, 0x43, 0x2e, 0x1c, 0xa2, 0x5e, 0x26, 0x92, 0x19, 0x93,
	0x71, 0x46, 0x35, 0x2a, 0xab, 0xc8, 0x29, 0x17, 0x76, 0xb3, 0xcb, 0xe9, 0x52, 0x49, 0x6a, 0x85,
	0xcc, 0x19, 0x5a, 0x25, 0xb9, 0xcc, 0x37, 0xb4, 0x10, 0xc6, 0x8a, 0x2d, 0x37, 0x83, 0xb7, 0x0a,
	0x74, 0x1e, 0x4a, 0x31, 0xd5, 0x56, 0xa8, 0xad, 0x21, 0x04, 0x6a, 0x3a, 0xe3, 0x2c, 0x0c, 0xa2,
	0x20, 0x3e, 0x48, 0xfd, 0x4c, 0x8e, 0xa1, 0xa9, 0x19, 0x2e, 0xbc, 0x5f, 0xf1, 0x7e, 0x43, 0x33,
	0x9c, 0xb9, 0xd5, 0x13, 0x34, 0xd6, 0xa2, 0xb0, 0x0c, 0x4d, 0x08, 0x51, 0x35, 0x6e, 0x8f, 0xae,
	0xe9, 0xaf, 0xb5, 0xf4, 0x67, 0x25, 0x9d, 0xf8, 0x80, 0x59, 0x86, 0x99, 0x4c, 0xf7, 0x69, 0xe4,
	0x04, 0xc0, 0x28, 0xb4, 0x8b, 0xb5, 0x60, 0xc5, 0x2a, 0xec, 0x45, 0x41, 0xdc, 0x4a, 0x5b, 0xce,
	0x99, 0x38, 0x83, 0x3c, 0x7e, 0xac, 0x15, 0xae, 0x18, 0x86, 0x47, 0x51, 0x10, 0x77, 0x46, 0x97,
	0x7f, 0xaf, 0x9e, 0xba, 0xe7, 0x65, 0xae, 0x1f, 0xfb, 0x57, 0xd0, 0xfe, 0x86, 0x43, 0x7a, 0x50,
	0x2f, 0x01, 0x02, 0x0f, 0x50, 0x0a, 0xe7, 0xbe, 0xec, 0x18, 0xbe, 0xfa, 0xcf, 0x68, 0xa5, 0xa5,
	0x18, 0xf4, 0xa1, 0xee, 0x33, 0x48, 0x03, 0xaa, 0x37, 0xf3, 0x71, 0xf7, 0x1f, 0x69, 0x42, 0xed,
	0xee, 0x7e, 0x3e, 0xee, 0x06, 0xb7, 0xe7, 0xcf, 0x67, 0x5f, 0x6c, 0xc9, 0x27, 0xdb, 0xd0, 0xc1,
	0x25, 0x5c, 0x0d, 0xf7, 0x7c, 0x09, 0xea, 0x65, 0xfe, 0xdf, 0xdf, 0xef, 0xe2, 0x3d, 0x00, 0x00,
	0xff, 0xff, 0xef, 0xa6, 0xaa, 0x28, 0xd4, 0x01, 0x00, 0x00,
}
