// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/simple/simple.proto

package simple

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Simple struct {
	Some                 int32    `protobuf:"varint,1,opt,name=some,proto3" json:"some,omitempty"`
	More                 uint64   `protobuf:"varint,2,opt,name=more,proto3" json:"more,omitempty"`
	Basic                string   `protobuf:"bytes,3,opt,name=basic,proto3" json:"basic,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Simple) Reset()         { *m = Simple{} }
func (m *Simple) String() string { return proto.CompactTextString(m) }
func (*Simple) ProtoMessage()    {}
func (*Simple) Descriptor() ([]byte, []int) {
	return fileDescriptor_24a8fd818dfa3a58, []int{0}
}

func (m *Simple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Simple.Unmarshal(m, b)
}
func (m *Simple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Simple.Marshal(b, m, deterministic)
}
func (m *Simple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Simple.Merge(m, src)
}
func (m *Simple) XXX_Size() int {
	return xxx_messageInfo_Simple.Size(m)
}
func (m *Simple) XXX_DiscardUnknown() {
	xxx_messageInfo_Simple.DiscardUnknown(m)
}

var xxx_messageInfo_Simple proto.InternalMessageInfo

func (m *Simple) GetSome() int32 {
	if m != nil {
		return m.Some
	}
	return 0
}

func (m *Simple) GetMore() uint64 {
	if m != nil {
		return m.More
	}
	return 0
}

func (m *Simple) GetBasic() string {
	if m != nil {
		return m.Basic
	}
	return ""
}

func (m *Simple) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Simple)(nil), "github.com.timbertomgmbh.crud.examples.simple.Simple")
}

func init() {
	proto.RegisterFile("examples/simple/simple.proto", fileDescriptor_24a8fd818dfa3a58)
}

var fileDescriptor_24a8fd818dfa3a58 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xbd, 0x0a, 0xc2, 0x30,
	0x14, 0x85, 0x89, 0xb6, 0x05, 0x33, 0x06, 0x87, 0x0c, 0x0e, 0xc5, 0xa9, 0x4b, 0x13, 0xa4, 0x6f,
	0xe0, 0x23, 0xd4, 0x4d, 0x5c, 0x9a, 0x7a, 0x69, 0x03, 0xbd, 0xdc, 0x92, 0xa4, 0xe2, 0xe3, 0x4b,
	0x52, 0x7f, 0xc0, 0xe9, 0xfc, 0xc0, 0x81, 0xef, 0xf0, 0x03, 0x3c, 0x3b, 0x9c, 0x27, 0xf0, 0xda,
	0xdb, 0xa8, 0x6f, 0x51, 0xb3, 0xa3, 0x40, 0xa2, 0x1e, 0x6c, 0x18, 0x17, 0xa3, 0x7a, 0x42, 0x15,
	0x2c, 0x1a, 0x70, 0x81, 0x70, 0x40, 0x33, 0xaa, 0xde, 0x2d, 0x77, 0xf5, 0xd9, 0xaa, 0x75, 0x74,
	0xbc, 0xf1, 0xe2, 0x92, 0x9c, 0x10, 0x3c, 0xf3, 0x84, 0x20, 0x59, 0xc9, 0xaa, 0xbc, 0x4d, 0x3e,
	0x76, 0x48, 0x0e, 0xe4, 0xa6, 0x64, 0x55, 0xd6, 0x26, 0x2f, 0xf6, 0x3c, 0x37, 0x9d, 0xb7, 0xbd,
	0xdc, 0x96, 0xac, 0xda, 0xb5, 0x6b, 0x88, 0xed, 0xa3, 0x9b, 0x16, 0x90, 0xd9, 0xda, 0xa6, 0x70,
	0x6e, 0xae, 0xa7, 0x1f, 0x8e, 0xfe, 0xe2, 0xd4, 0x91, 0x47, 0x0f, 0x54, 0x47, 0x24, 0xfd, 0x77,
	0xc7, 0x14, 0xe9, 0x48, 0xf3, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x87, 0xd4, 0x21, 0x29, 0xe8, 0x00,
	0x00, 0x00,
}
